-- Create Books Table
CREATE TABLE Books (
  BOOK_ID SERIAL PRIMARY KEY,
  TITLE VARCHAR(100),
  AUTHOR VARCHAR(100),
  GENRE VARCHAR(50),
  YEAR_PUBLISHED INT,
  AVAILABLE_COPIES INT
);

-- Create Members Table
CREATE TABLE Members (
  MEMBER_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100),
  EMAIL VARCHAR(100),
  PHONE_NO VARCHAR(15),
  ADDRESS TEXT,
  MEMBERSHIP_DATE DATE
);

-- Create BorrowingRecords Table
CREATE TABLE BorrowingRecords (
  BORROW_ID SERIAL PRIMARY KEY,
  MEMBER_ID INT REFERENCES Members(MEMBER_ID),
  BOOK_ID INT REFERENCES Books(BOOK_ID),
  BORROW_DATE DATE,
  RETURN_DATE DATE
);
