CREATE DATABASE OnlineStore;

\c OnlineStore

-- Customers table
CREATE TABLE Customers (
  CUSTOMER_ID SERIAL PRIMARY KEY,
  NAME TEXT,
  EMAIL TEXT,
  PHONE TEXT,
  ADDRESS TEXT
);

-- Products table
CREATE TABLE Products (
  PRODUCT_ID SERIAL PRIMARY KEY,
  PRODUCT_NAME TEXT,
  CATEGORY TEXT,
  PRICE NUMERIC,
  STOCK INT
);

-- Orders table
CREATE TABLE Orders (
  ORDER_ID SERIAL PRIMARY KEY,
  CUSTOMER_ID INT REFERENCES Customers(CUSTOMER_ID),
  PRODUCT_ID INT REFERENCES Products(PRODUCT_ID),
  QUANTITY INT,
  ORDER_DATE DATE
);
